const ADD_BOUNTY = 'ADD_BOUNTY';
// Meta Mask Stuff
const GET_METAMASK_ACCOUNTS = 'GET_METAMASK_ACCOUNTS';
const GET_METAMASK_ACCOUNTS_SUCCESS = 'GET_METAMASK_ACCOUNTS_SUCCESS';
// Fetch bounty ids
const FETCH_BOUNTY_IDS = 'FETCH_BOUNTY_IDS';
const FETCH_BOUNTY_IDS_FAILED = 'FETCH_BOUNTY_IDS_FAILED';
const FETCH_BOUNTY_IDS_SUCCESS = 'FETCH_BOUNTY_IDS_SUCCESS';
// Fetch single bounty info
const FETCH_BOUNTY = 'FETCH_BOUNTY';
const FETCH_BOUNTY_SUCCESS = 'FETCH_BOUNTY_SUCCESS';
const FETCH_BOUNTY_FAILED = 'FETCH_BOUNTY_FAILED';
// Create Bounty
const CREATE_BOUNTY = 'CREATE_BOUNTY';
const CREATE_BOUNTY_SUCCESS = 'CREATE_BOUNTY_SUCCESS';
const CREATE_BOUNTY_FAILED = 'CREATE_BOUNTY_FAILED';

export default {
  GET_METAMASK_ACCOUNTS,
  GET_METAMASK_ACCOUNTS_SUCCESS,
  ADD_BOUNTY,
  FETCH_BOUNTY_IDS,
  FETCH_BOUNTY_IDS_FAILED,
  FETCH_BOUNTY_IDS_SUCCESS,
  FETCH_BOUNTY,
  FETCH_BOUNTY_SUCCESS,
  FETCH_BOUNTY_FAILED,
  CREATE_BOUNTY,
  CREATE_BOUNTY_SUCCESS,
  CREATE_BOUNTY_FAILED
};
